# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Mann Robotics
email: contact@mannrobo.org
description: >- # this means to ignore newlines until "baseurl:"
  Mann Robotics is a competitive robotics organization at J.L. Mann High School in Greenville, SC.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mannrobo.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mannrobo
github_username: mannrobo

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

links:
  - title: About
    href: "/about/"
  - title: Calendar
    href: "/calendar/"

  - title: Teams
    children:
      - title: 3796A
        href: /teams/3796A/
      - title: 3796B
        href: /teams/3796B/
      - title: 3796C
        href: /teams/3796C/

  - title: Events
    children:
      - title: Mann Robotics Fall Qualifier
        href: https://www.robotevents.com/robot-competitions/vex-robotics-competition/RE-VRC-18-5641.html
        external: true
      - title: Mann Robotics Upstate Qualifier
        href: https://www.robotevents.com/robot-competitions/vex-robotics-competition/RE-VRC-18-5657.html
        external: true
      - title: Volunteer
        href: /volunteer/

  - title: Community
    children:
      - title: Falcon's Middle School Qualifier
        href: /community/falcons/
      - title: BCUZ at Clemson University
        href: /community/bcuz/
      - title: Sponsorships
        href: /community/sponsors/

  - title: Contact
    children:
      - title: Join Us!
        href: https://link.mannrobo.org/join/
        external: true
      - title: General Contact
        href: /contact/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
